# Generated by Django 4.2.4 on 2023-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_globalsettings_sitefax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Vision', 'Vision'), ('Mission', 'Mission'), ('Home/About', 'Home/About'), ('Documents', 'Documents'), ('About Company', 'About Company'), ('Overseas Services 1', 'Overseas Services 1'), ('About', 'About'), ('Our Message', 'Our Message'), ('Our Commitment', 'Our Commitment'), ('Contact', 'Contact'), ('Organizational Chart', 'Organizational Chart'), ('Demand Letter', 'Demand Letter'), ('Job Seeker', 'Job Seeker'), ('Recruiting Procedure', 'Recruiting Procedure'), ('Recruiting Documents', 'Recruiting Documents'), ('Gallery', 'Gallery'), ('Slider', 'Slider'), ('Service', 'Service'), ('Overseas Services', 'Overseas Services'), ('Newspaper Vacancy', 'Newspaper Vacancy'), ('Our Service', 'Our Service'), ('Requirement', 'Requirement'), ('Group', 'Group'), ('Normal', 'Normal'), ('Talent', 'Talent'), ('UNSKILLED', 'UNSKILLED'), ('THE PROFESSIONALS', 'THE PROFESSIONALS'), ('Instructors', 'Instructors'), ('News', 'News'), ('TESTIMONIAL', 'TESTIMONIAL'), ('Home1', 'Home1'), ('Job', 'Job'), ('Job1', 'Job1'), ('Job2', 'Job2'), ('Job3', 'Job3'), ('News', 'News'), ('Gall', 'Gall'), ('Job Details', 'Job Details'), ('Home2', 'Home2'), ('Home3', 'Home3'), ('Home4', 'Home4'), ('Home5', 'Home5'), ('Home6', 'Home6'), ('Job Vacancy', 'Job Vacancy'), ('Job List', 'Job List')], max_length=50, null=True),
        ),
    ]
