# Generated by Django 4.2.4 on 2023-08-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Vision', 'Vision'), ('Mission', 'Mission'), ('Home/About', 'Home/About'), ('Documents', 'Documents'), ('About Company', 'About Company'), ('Overseas Services 1', 'Overseas Services 1'), ('About', 'About'), ('Our Message', 'Our Message'), ('Our Commitment', 'Our Commitment'), ('Contact', 'Contact'), ('Organizational structure', 'Organizational structure'), ('Demand Letter', 'Demand Letter'), ('Job Seeker', 'Job Seeker'), ('Recruiting Procedure', 'Recruiting Procedure'), ('Recruiting Documents', 'Recruiting Documents'), ('Gallery', 'Gallery'), ('Slider', 'Slider'), ('Service', 'Service'), ('Overseas Services', 'Overseas Services'), ('Newspaper Vacancy', 'Newspaper Vacancy'), ('Our Service', 'Our Service'), ('Requirement', 'Requirement'), ('Group', 'Group'), ('Normal', 'Normal'), ('Talent', 'Talent'), ('UNSKILLED', 'UNSKILLED'), ('THE PROFESSIONALS', 'THE PROFESSIONALS'), ('Instructors', 'Instructors'), ('News', 'News'), ('Clients Say', 'Clients Say'), ('Home1', 'Home1'), ('Job', 'Job'), ('Our Mission', 'Our Mission'), ('Client', 'Client'), ('Job3', 'Job3'), ('News', 'News'), ('Gall', 'Gall'), ('Job Details', 'Job Details'), ('Client1', 'Client1'), ('Client2', 'Client2'), ('Legal Document', 'Legal Document'), ('Message', 'Message'), ('Our Vision', 'Our Vision'), ('Job Vacancy', 'Job Vacancy'), ('Job List', 'Job List')], max_length=50, null=True),
        ),
    ]
